version: '3'
services:
    nginx:
        image: nginx 
        ports:
            - "8090:80"
        links:
            - php-fpm
        volumes:
            - ./nginx/www:/var/www/html
            - ./nginx/sites:/etc/nginx/sites-enabled
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    php-fpm:
        image: 'bitnami/php-fpm:7.1'
        volumes:
            - ./nginx/www:/var/www/html
            - ./php-fpm/php.ini:/bitnami/php/conf/php.ini
        links:
            - mysql
            - redis

    mysql:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
        volumes:
            - ./mysql:/var/lib/mysql


    redis:
        image: redis

